src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $ordre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\ManyToOne]
    private ?CategorieDeServices $categorie_service = null;

    #[ORM\ManyToOne]
    private ?Prestataire $prestataire = null;

    #[ORM\ManyToOne]
    private ?Internaute $internaute = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(?int $ordre): self
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategorieService(): ?CategorieDeServices
    {
        return $this->categorie_service;
    }

    public function setCategorieService(?CategorieDeServices $categorie_service): self
    {
        $this->categorie_service = $categorie_service;

        return $this;
    }

    public function getPrestataire(): ?Prestataire
    {
        return $this->prestataire;
    }

    public function setPrestataire(?Prestataire $prestataire): self
    {
        $this->prestataire = $prestataire;

        return $this;
    }

    public function getInternaute(): ?Internaute
    {
        return $this->internaute;
    }

    public function setInternaute(?Internaute $internaute): self
    {
        $this->internaute = $internaute;

        return $this;
    }
}

src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StageRepository::class)]
class Stage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $tarif = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $info_complementaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fin = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $affichage_de = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $affichage_jusque = null;

    #[ORM\ManyToOne(inversedBy: 'stages')]
    private ?Prestataire $prestataire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTarif(): ?string
    {
        return $this->tarif;
    }

    public function setTarif(?string $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getInfoComplementaire(): ?string
    {
        return $this->info_complementaire;
    }

    public function setInfoComplementaire(?string $info_complementaire): self
    {
        $this->info_complementaire = $info_complementaire;

        return $this;
    }

    public function getDebut(): ?\DateTimeInterface
    {
        return $this->debut;
    }

    public function setDebut(?\DateTimeInterface $debut): self
    {
        $this->debut = $debut;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(?\DateTimeInterface $fin): self
    {
        $this->fin = $fin;

        return $this;
    }

    public function getAffichageDe(): ?\DateTimeInterface
    {
        return $this->affichage_de;
    }

    public function setAffichageDe(?\DateTimeInterface $affichage_de): self
    {
        $this->affichage_de = $affichage_de;

        return $this;
    }

    public function getAffichageJusque(): ?\DateTimeInterface
    {
        return $this->affichage_jusque;
    }

    public function setAffichageJusque(?\DateTimeInterface $affichage_jusque): self
    {
        $this->affichage_jusque = $affichage_jusque;

        return $this;
    }

    public function getPrestataire(): ?Prestataire
    {
        return $this->prestataire;
    }

    public function setPrestataire(?Prestataire $prestataire): self
    {
        $this->prestataire = $prestataire;

        return $this;
    }
}

src/Controller/PrestataireController.php
<?php

namespace App\Controller;

use App\Repository\PrestataireRepository;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Images;
use App\Entity\Proposer;
use App\Entity\Prestataire;
use App\Entity\Promotion;
use App\Entity\Stage;
use App\Entity\Utilisateur;
use App\Service\PictureService;
use App\Form\PrestataireFormType;
use App\Form\PrestataireSearchType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;





class PrestataireController extends AbstractController
{



    #[Route('/devenir-prestataire', name: 'app_prestataire_form')]
    public function devenirPrestataire(Request $request, EntityManagerInterface $entityManager, PictureService $pictureService): Response
    {

        $prestataire = new Prestataire();
        $form = $this->createForm(PrestataireFormType::class, $prestataire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //On récupère les images
            $images = $form->get('images')->getData();
            foreach ($images as $image) {
                //On définit le dossier de destination
                $folder = 'prestataires';
                //On appelle le service d'ajout
                $fichier = $pictureService->add($image, $folder, 300, 300);

                $img = new Images();
                $img->setNom($fichier);
                $prestataire->addImage($img);
            }

            //changer le rôle de l'utilisateur
            $id = $this->getUser()->getId();
            $repository = $entityManager->getRepository(Utilisateur::class);
            $utilisateur = $repository->find($id);
            $utilisateur->setRoles(['ROLE_PRESTATAIRE']);

            $prestataire->setUtilisateur($this->getUser());

            // Récupérer les catégories sélectionnées dans le formulaire
            $categories = $form->get('categories')->getData();

            // Mettre à jour la table proposer pour lier les catégories au prestataire
            foreach ($categories as $category) {
                $proposer = new Proposer();
                $proposer->setPrestataire($prestataire);
                $proposer->setCategorieService($category);
                $entityManager->persist($proposer);
            }

            $entityManager->persist($prestataire);
            $entityManager->flush();

            $this->addFlash('Succès', 'Votre demande pour devenir prestataire a bien été enregistrée.');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('prestataire/inscription.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/prestataires', name: 'app_prestataire_liste')]
    public function index(EntityManagerInterface $entityManager, Request $request, PrestataireRepository $prestataireRepository, PaginatorInterface $paginator): Response
    {

        $form = $this->createForm(PrestataireSearchType::class);
        $form->handleRequest($request);

        // Si le formulaire est soumis, exécuter la recherche et afficher les résultats
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $nom = $data['nom'];
            $categories = $data['categories'] ? $data['categories']->getId() : null;
            $localite = $data['localite'] ? $data['localite']->getId() : null;
            $codePostal = $data['codePostal'] ? $data['codePostal']->getId() : null;
            $commune = $data['commune'] ? $data['commune']->getId() : null;

            $prestataires = $prestataireRepository->findByFilters($nom, $categories, $localite, $codePostal, $commune);
            $pagination = $paginator->paginate(
                $prestataires,
                $request->query->getInt('page', 1), // Numéro de page à afficher
                12
            ); // Nombre de résultats par page

            // Afficher les résultats de la recherche
            return $this->render('prestataire/recherche.html.twig', [
                'prestataires' => $prestataires,
                'form' => $form->createView(),
                'pagination' => $pagination
            ]);
        }

        $repository = $entityManager->getRepository(Prestataire::class);
        $prestataires = $repository->findBy([]);

        return $this->render('prestataire/liste.html.twig', [
            'prestataires' => $prestataires,
            'form' => $form->createView()



        ]);;
    }

    #[Route('/prestataires/profil/{id}', name: 'app_prestataire_detail')]
    public function show(EntityManagerInterface $entityManager, int $id, PrestataireRepository $prestataireRepository): Response
    {

        $prestataire = $entityManager->getRepository(Prestataire::class)
            ->createQueryBuilder('p')
            ->leftJoin('p.utilisateur', 'u')
            ->addSelect('u')
            ->leftJoin('u.commune', 'c')
            ->addSelect('c')
            ->leftJoin('u.localite', 'l')
            ->addSelect('l')
            ->leftJoin('u.code_postal', 'cp')
            ->addSelect('cp')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();

        $categories = $entityManager->getRepository(Proposer::class)->findCategoriesByPrestataireId($id);

        $currentDate = new \DateTime();

        $promotions = $entityManager->getRepository(Promotion::class)
            ->createQueryBuilder('p')
            ->leftJoin('p.categorie_service', 'cs')
            ->addSelect('cs')
            ->where('p.prestataire = :prestataire_id')
            ->andWhere('p.affichage_de <= :current_date')
            ->andWhere('p.affichage_jusque >= :current_date')
            ->setParameter('prestataire_id', $id)
            ->setParameter('current_date', $currentDate)
            ->getQuery()
            ->getResult();



        $stages = $entityManager->getRepository(Stage::class)
            ->createQueryBuilder('s')
            ->where('s.prestataire = :prestataire_id')
            ->andWhere('s.affichage_de <= :current_date')
            ->andWhere('s.affichage_jusque >= :current_date')
            ->setParameter('prestataire_id', $id)
            ->setParameter('current_date', $currentDate)
            ->getQuery()
            ->getResult();


        $images = [
            'image1.jpg',
            'image2.jpg',
            'image3.jpg',
            'image4.jpg',
            'image5.jpg',
            'image6.jpg',

        ];

        $prestatairesSimilaires = $prestataireRepository->findPrestatairesSimilaires($prestataire);




        return $this->render('prestataire/detail.html.twig', [
            'prestataire' => $prestataire,
            'categories' => $categories,
            'stages' => $stages,
            'promotions' => $promotions,
            'images' => $images,
            'prestatairesSimilaires' => $prestatairesSimilaires,


        ]);
    }

    #[Route('/prestataires/promotion', name: 'app_promotion_telechargement')]
    public function telechargement(string $pdf): BinaryFileResponse
    {
        $cheminFichier = $this->getParameter('chemin_dossier_promotions') . '/' . $pdf;

        $response = new BinaryFileResponse($cheminFichier);
        $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, $pdf);

        return $response;
    }



    /*#[Route('/prestataires/recherche', name: 'app_prestataire_recherche')]
    public function search(Request $request, PrestataireRepository $prestataireRepository, PaginatorInterface $paginator): Response
    {
        // Créer un formulaire de recherche de prestataires
        $form = $this->createForm(PrestataireSearchType::class);
        $form->handleRequest($request);

        // Si le formulaire est soumis, exécuter la recherche et afficher les résultats
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $nom = $data['nom'];
            $categories = $data['categories']->toArray();
            $localite = $data['localite'] ? $data['localite']->getId() : null;
            $codePostal = $data['codePostal'] ? $data['codePostal']->getId() : null;
            $commune = $data['commune'] ? $data['commune']->getId() : null;

            $prestataires = $prestataireRepository->findByFilters($nom, $categories, $localite, $codePostal, $commune);
            $pagination = $paginator->paginate(
                $prestataires,
                $request->query->getInt('page', 1), // Numéro de page à afficher
                10
            ); // Nombre de résultats par page

            // Afficher les résultats de la recherche
            return $this->render('prestataire/liste.html.twig', [
                'prestataires' => $prestataires,
                'form' => $form->createView(),
                'pagination' => $pagination
            ]);
        }

        // Afficher le formulaire de recherche
        return $this->render('components/_search_presta.html.twig', [
            'form' => $form->createView()
        ]);
    }*/
}

templates/prestataire/detail.html.twig
{% extends "base.html.twig" %}


{% block body %}

	<div class="container">

		<section class="text-center my-4">
			{% for image in prestataire.images %}
				<img src="{{ asset('uploads/prestataires/' ~ image.nom) }}" class="img-fluid rounded-circle" style="width: 200px; height: 200px" alt="Photo du prestataire">
			{% endfor %}
			<h1 class="mt-3">{{ prestataire.nom }}</h1>
		</section>

		<section class="my-5">
			<div class="row text-center">
				<div class="col-md-6">
					{% if prestataire.numtel is not null %}
						<p>
							<strong>Téléphone :</strong>
							{{ prestataire.numtel }}</p>
					{% else %}
						<p>
							<strong>Téléphone :</strong>
							/
						</p>
					{% endif %}

					{% if prestataire.utilisateur.email is not null %}
						<p>
							<strong>Email :</strong>
							{{ prestataire.utilisateur.email }}</p>
					{% else %}
						<p>
							<strong>Email :</strong>
							/
						</p>
					{% endif %}

					<p>
						<strong>Adresse :
						</strong>
						{{ prestataire.utilisateur.adresserue }}
						{{ prestataire.utilisateur.adressenum }}
					</p>


					{% if prestataire.utilisateur.commune is not null %}
						<p>
							<strong>Commune :</strong>
							{{ prestataire.utilisateur.commune.commune }}</p>
					{% else %}
						<p>
							<strong>Commune :</strong>
							/
						</p>
					{% endif %}
				</div>
				<div class="col-md-6">
					{% if prestataire.utilisateur.localite is not null %}
						<p>
							<strong>Localité :</strong>
							{{ prestataire.utilisateur.localite.localite }}</p>
					{% else %}
						<p>
							<strong>Localité :</strong>
							/
						</p>
					{% endif %}


					{% if prestataire.utilisateur.codepostal is not null %}
						<p>
							<strong>Code Postal :</strong>
							{{ prestataire.utilisateur.codepostal.codepostal }}</p>
					{% else %}
						<p>
							<strong>Code Postal :</strong>
							/
						</p>
					{% endif %}


					{% if prestataire.numtva is not null %}
						<p>
							<strong>Numéro de TVA :</strong>
							{{ prestataire.numtva }}</p>
					{% else %}
						<p>
							<strong>Numéro de TVA :</strong>
							/
						</p>
					{% endif %}

					{% if prestataire.siteinternet is not null %}
						<p>
							<strong>Site internet :</strong>
							<a href="https://www.google.be/" target="blank">{{ prestataire.siteinternet }}</a>
						</p>
					{% else %}
						<p>
							<strong>Site internet :</strong>
							/
						</p>
					{% endif %}


				</div>
			</div>
		</section>

		<section class="text-center my-5">
			<h2 class="mb-3">Services proposés</h2>
			{% if categories|length > 0 %}
				<div class="row">
					{% for category in categories %}
						<div class="col-md-3 mb-4 mx-auto ">
							<div class="card " style="width: 18rem;">
								<img src="{{ asset('images/Massage_thérapeutique1.jpg') }}" class="card-img-top" alt=""/>
								<div class="card-body">
									<h5 class="card-title">{{ category.nom }}</h5>
									<p>{{category.description}}</p>
									<a href={{path('app_categorie_detail',{'id': category.id} )}} class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Voir plus</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			{% else %}
				<div class="alert alert-warning" role="alert">
					Ce prestataire ne propose pas encore de service pour le moment.
				</div>
			{% endif %}
		</section>


		<section class='mb-5'>
			<h2 class="mb-3">Stages proposé</h2>
			{% if stages|length > 0 %}
				<div class="row">
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th>Date de début</th>
								<th>Date de fin</th>
								<th>Nom</th>
								<th>Description</th>
								<th>Tarif</th>
								<th>Info complémentaire</th>
							</tr>
						</thead>
						<tbody>
							{% for stage in stages %}
								<tr>
									<td>{{ stage.debut|date('d-m-Y') }}</td>
									<td>{{ stage.fin|date('d-m-Y') }}</td>
									<td>{{ stage.nom }}</td>
									<td>{{ stage.description }}</td>
									<td>{{ stage.tarif }}€</td>
									<td>{{ stage.infoComplementaire }}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>

			{% else %}
				<div class="alert alert-warning" role="alert">
					Ce prestataire ne propose pas de stages pour le moment.
				</div>
			{% endif %}


		</section>
		<section class='mb-5'>
			<h2 class="mb-3">Promotion du moment</h2>
			{% if promotions|length > 0 %}
				<div class="row">
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th>Date de début</th>
								<th>Date de fin</th>
								<th>Nom</th>
								<th>Description</th>
								<th>Catégorie</th>
								<th>Doc</th>
							</tr>
						</thead>
						<tbody>
							{% for promotion in promotions %}
								<tr>
									<td>{{ promotion.debut|date('d-m-Y') }}</td>
									<td>{{ promotion.fin|date('d-m-Y') }}</td>
									<td>{{ promotion.nom }}</td>
									<td>{{ promotion.description }}</td>
									<td>{{ promotion.categorieService.nom }}</td>
									<td>
										<a href="{{ path('app_promotion_telechargement', { 'pdf': promotion.pdf }) }}" download class="btn btn-primary">Télécharger</a>
									</td>

								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>

			{% else %}
				<div class="alert alert-warning" role="alert">
					Ce prestataire ne propose pas de stages pour le moment.
				</div>
			{% endif %}


		</section>

		<section class='mb-5'>
			<div id="carouselExample" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					{% for index, image in images %}
						<li data-target="#carouselExample" data-slide-to="{{ index }}" {% if loop.first %} class="active" {% endif %}></li>
					{% endfor %}
				</ol>
				<div class="carousel-inner">
					{% for index, image in images %}
						<div class="carousel-item {% if loop.first %}active{% endif %}">
							<img src="{{ asset('uploads/prestataires/gallerie/' ~ image) }}" class="d-block w-100" alt="Image">
						</div>
					{% endfor %}
				</div>
				<a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</section>
		<section class="text-center my-5">
			<h2 class="mb-3 ">Prestataire similaire</h2>
			{% if prestatairesSimilaires|length > 0 %}
				<div class="container">
					<div class="row">
						{% for prestataireSimilaire in prestatairesSimilaires %}
							<div class="col-md-3 mb-4 mx-auto">
								<div class="text-center">
									{% for image in prestataireSimilaire.images %}
										<img src="{{ asset('uploads/prestataires/mini/300x300-' ~ image.nom) }}" class="rounded-circle mb-1" alt="Photo de profil de {{ prestataireSimilaire.nom }}" style="width: 150px; height: 150px;">
									{% endfor %}
								</div>
								<div class="card-body text-center">
									<h5 class="card-title mb-2">{{ prestataireSimilaire.nom }}</h5>
									<a href="{{ path('app_prestataire_detail', {'id': prestataireSimilaire.id}) }}" class="rounded-pill btn btn-success btn-block btn-lg gradient-custom-4 text-body">Découvrir</a>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			{% else %}
				<div class="alert alert-warning" role="alert">
					Ce prestataire ne propose pas encore de service pour le moment.
				</div>
			{% endif %}
		</section>
	</div>

</div></div>{% endblock %}

templates/prestataire/inscription.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('styles/register_form.css') }}">
{% endblock %}

{% block body %}
	<div class=" mx-auto" style="max-width: 600px;">
		<div class="card-header bg-white text-center">
			<h1 class="text-uppercase text-center mb-5">S'inscrire comme pestataire</h1>
		</div>
		{{ form_start(form) }}
		<div class="form-outline mb-4">
			{{ form_widget(form.nom, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Nom'}}) }}
		</div>
		<div class="form-outline mb-4">

			{{ form_widget(form.site_internet, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Site Internet'}}) }}
		</div>
		<div class="form-outline mb-4">

			{{ form_widget(form.num_tel, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Numéro de téléhphonne'}}) }}
		</div>
		<div class="form-outline mb-4">
			{{ form_widget(form.num_tva, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Numéro de TVA'}}) }}
		</div>
		<div class="form-outline mb-4">
			{{ form_widget(form.categories, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Categories'}}) }}
		</div>
		<div class="form-outline mb-4">
			{{ form_widget(form.images, {'attr': {'class': 'form-control form-control-lg', 'placeholder': 'Photo de profil'}}) }}
		</div>
		<div class="d-flex justify-content-center">
			<button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Devenir prestataire</button>
		</div>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/prestataire/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestataires
{% endblock %}

{% block body %}
	<header>
		<img src="{{ asset('images/background_prestataires.jpg') }}" alt="Description de l'image" style=" height: 500px; object-fit: cover; width: 100%;">
	</header>
	{% include "components/_search_presta.html.twig" with{
		form : form
	} %}
	<main class="categories">
		<h1 class='text-center mb-5'>Nos prestataires</h1>
		<div class="container">
			<div class="row">
				{% for prestataire in prestataires %}
					<div class="col-md-3 mb-4 mx-auto">
						<div class="text-center">
							{% for image in prestataire.images %}
								<img src="{{ asset('uploads/prestataires/mini/300x300-' ~ image.nom) }}" class="rounded-circle mb-1" alt="Photo de profil de {{ prestataire.nom }}" style="width: 150px; height: 150px;">
							{% endfor %}
						</div>
						<div class="card-body text-center">
							<h5 class="card-title mb-2">{{ prestataire.nom }}</h5>
							<a href="{{ path('app_prestataire_detail', {'id': prestataire.id}) }}" class="rounded-pill btn btn-success btn-block btn-lg gradient-custom-4 text-body">Découvrir</a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</main>
{% endblock %}

templates/prestataire/recherche.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestataires
{% endblock %}

{% block body %}
	{% include "components/_search_presta.html.twig" with{
		form : form
	} %}
	<main class="categories">
		<h1 class='text-center mb-5'>Prestataires trouvés</h1>
		<div class="container">
			<div class="row">
				{% for prestataire in pagination %}
					<div class="col-md-3 mb-4 mx-auto">
						<div class="text-center">
							{% for image in prestataire.images %}
								<img src="{{ asset('uploads/prestataires/mini/300x300-' ~ image.nom) }}" class="rounded-circle mb-1" style="width: 150px; height: 150px;" alt=""/>
							{% endfor %}
						</div>
						<div class="card-body text-center">
							<h5 class="card-title mb-2">{{ prestataire.nom }}</h5>
							<a href={{path('app_prestataire_detail',{'id': prestataire.id} )}} class="rounded-pill btn btn-success btn-block btn-lg gradient-custom-4 text-body">Découvrir</a>
						</div>
					</div>
				{% endfor %}
			</div>
			<div>
				{{ knp_pagination_render(pagination) }}
			</div>
		</div>

	</main>
{% endblock %}