src/Entity/CodePostal.php
<?php

namespace App\Entity;

use App\Repository\CodePostalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CodePostalRepository::class)]
class CodePostal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 4, nullable: true, unique: true)]
    private ?string $code_postal = null;

    #[ORM\OneToMany(mappedBy: 'code_postal', targetEntity: Utilisateur::class)]
    private Collection $utilisateurs;

    public function __construct()
    {
        $this->utilisateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }
    public function __toString()
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection<int, Utilisateur>
     */
    public function getUtilisateurs(): Collection
    {
        return $this->utilisateurs;
    }

    public function addUtilisateur(Utilisateur $utilisateur): self
    {
        if (!$this->utilisateurs->contains($utilisateur)) {
            $this->utilisateurs->add($utilisateur);
            $utilisateur->setCodePostal($this);
        }

        return $this;
    }

    public function removeUtilisateur(Utilisateur $utilisateur): self
    {
        if ($this->utilisateurs->removeElement($utilisateur)) {
            // set the owning side to null (unless already changed)
            if ($utilisateur->getCodePostal() === $this) {
                $utilisateur->setCodePostal(null);
            }
        }

        return $this;
    }
}

templates/components/_header.html.twig
<header>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href={{path('app_home')}}>
				<img class="d-block w-50" src="{{ asset('images/logo.png')}}" alt="First slide">
			</a>

			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mx-auto mb-2 mb-md-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href={{path('app_home')}}>Accueil</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href={{path('app_categorie_liste')}}>Catégories</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href={{path('app_prestataire_liste')}}>Prestataires</a>
					</li>
				</ul>
				{% if is_granted('IS_AUTHENTICATED_FULLY') %}
					{% if app.user.prestataire %}
						<a href='#' class="btn btn-success me-2" type="submit">Mon compte</a>
						<a href={{path('app_logout')}} class="btn btn-outline-danger  me-2" type="submit">Déconnexion</a>
					{% else %}
						<a href='#' class="btn btn-success me-2" type="submit">Mon compte</a>
						<a href={{path('app_prestataire_form')}} class="btn btn-outline-success  me-2" type="submit">Devenir Prestataire</a>
						<a href={{path('app_logout')}} class="btn btn-outline-danger  me-2" type="submit">Déconnexion</a>
					{% endif %}
				{% else %}
					<a href={{path('app_connexion')}} class="btn btn-outline-success  me-2" type="submit">Connexion</a>
					<a href={{path('app_inscription')}} class="btn btn-success" type="submit">Inscription</a>
				{% endif %}

			</div>
		</div>
	</nav>
</header>

templates/components/_search_presta.html.twig
{% block body %}
	{% block stylesheets %}<link rel="stylesheet" href="{{ asset('styles/register_form.css') }}">
	{% endblock %}
	<div class="container py-5 ">
		<div>
			<div>
				<h3>Trouver le prestataire qui vous convient !</h3>
			</div>
			<div>
				{{ form_start(form) }}
				<div class="row">
					<div class="col-md-6">
						{{ form_row(form.nom,{
							label: false,
							attr: {
                class: 'form-control mb-3'
            }
						}) }}
					</div>
					<div class="col-md-6">
						{{ form_row(form.categories,{
							label: false,
							attr: {
                class: 'form-control mb-3'
            }
						}) }}
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 mr-3">
						{{ form_row(form.localite, {
            label: false,
            attr: {
                class: 'form-control'
            }
        }) }}
					</div>
					<div class="col-md-4 ">
						{{ form_row(form.codePostal, {
            label: false,
            attr: {
                class: 'form-control'
            }
        }) }}
					</div>
					<div class="col-md-4">
						{{ form_row(form.commune, {
            label: false,
            attr: {
                class: 'form-control'
            }
        }) }}
					</div>
				</div>
				<div>
					<div>
						{{ form_rest(form) }}
					</div>
				</div>
				<div class="text-center">
					<button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body mt-2">Rechercher</button>
				</div>
				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}